---
title: "About me"
author: "Ari Decter-Frain"
date: "August 31, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I am a PhD candidate in the Cornell Brooks School of Public Policy, where I do research in economics and demography using computational methods. I have also interned as a Machine Learning Engineer at [Graphika Technologies](https://graphika.com/), and as a Research Scientist at [Spotify](https://open.spotify.com/?). I am currently seeking roles in the private sector. I hold an MSc in [Inequalities and Social Science](https://www.lse.ac.uk/study-at-lse/Graduate/Degree-programmes-2020/MSc-Inequalities-and-Social-Science) from the London School of Economics and a BA in Psychology from the [University of Winnipeg](https://www.uwinnipeg.ca/). 


## Timeline

_**Fall 2023**_

* Continuing on my dissertation work
* Began actively seeking private sector roles to start in 2024. Open to discussing any and all opportunities!

_**Spring and Summer 2023**_

* I spent the spring and summer working on my dissertation projects and doing research into different options for post-PhD careers.
* My first-authored paper [Comparing Methods for Estimating Demographics in Racially Polarized Voting Analyses](https://journals-sagepub-com.proxy.library.cornell.edu/doi/full/10.1177/00491241231192383) was published in the Journal Sociological Methods and Research
* My solo-authored paper [How should we proxy for race/ethnicity? Comparing Bayesian improved surname geocoding to machine learning methods](https://scholar.google.ca/citations?view_op=view_citation&hl=en&user=rR7W1D4AAAAJ&citation_for_view=rR7W1D4AAAAJ:qjMakFHDy7sC) was conditionally accepted at the journal Political Science Research Methods

_**Fall 2022**_

* I interned on Spotify's Content Platform Research team. I worked on fitting graph neural networks (GNNs) to music industry knowledge graphs (with PyTorch) to create embeddings and do link prediction. I met many wonderful, intelligent people, and had a great time learning about the inner workings of a really cool industry.
* I passed my PhD A-exam and moved to PhD candidacy!
* My co-authored paper with Arthur Acolin and Matt Hall, [Small-area estimates from consumer trace data](https://www-jstor-org.proxy.library.cornell.edu/stable/48708297?typeAccessWorkflow=login) was published in the journal Demographic Research.
* I presented my paper with Vlad Barash, Chief Scientist at Graphika Technologies, on [Using Knowledge Graphs to Detect Partisanship in Online Political Discourse](https://scholar.google.ca/citations?view_op=view_citation&hl=en&user=rR7W1D4AAAAJ&citation_for_view=rR7W1D4AAAAJ:W7OEmFMy1HYC)

_**Summer 2022**_

* I worked on mortality prediction and survival modelling at MPIDR in Rostock ([link to program](https://www.demogr.mpg.de/en/news_events_6123/news_press_releases_4630/news/population_and_social_data_science_summer_incubator_program_10619)).
* Paper on knowledge graph representations of online political discourse accepted to the The 11th International Conference on Complex Networks and their Applications! ([link to conference](https://complexnetworks.org/))
* Received a revise-and-resubmit for a co-authored applied demography paper!

_**Winter and Spring 2022**_

* Released two preprints about proxying race/ethnicity in political science ([here](https://osf.io/preprints/socarxiv/e854z/) and [here](https://arxiv.org/abs/2206.14583))

_**06/2021 - 12/2021: Summer and fall third year**_

* Worked as a Machine Learning Engineer at [Graphika](https://graphika.com/), building NLP classification models and methods for cross-platform clustering of social media data.
* RA for Dr. Matthew Hall on statistical models for the use of consumer data to measure population levels and migration flows.
* Wrote my second year paper, using machine learning to improve race-ethnicity imputation.

_**01/2021 - 05/2021: Spring of second year**_

* Awarded SSHRC Doctoral Fellowship, which will fund the next three years of my PhD! Thanks, Canada!
* Presented a poster entitled "Small Area Population Estimates from Consumer Data" (joint with Arthur Acolin and Matthew Hall) at the PAA 2021 annual conference
* Also presented the above at the APPAM 2021 Student Seminar Series
* Submitted the first paper of my PhD, collaborative work with my DSSG colleagues on measuring racially polarized voting and the racial composition of the voting population.
* TA'd Big Data for Policy Analysis

_**09/2020 - 12/2020: Fall of second year**_

* Assembled my committee: Professors Doug Miller (Chair), Michael Macy, and Matthew Hall
* TA'd Introduction to Statistics for PAM Majors
* Presented ongoing research with my DSSG colleagues at [PRIEC](http://priec.org/)

_**06/2020 - 08/2020: Data Science for Social Good**_

* Developed an [R package](https://github.com/RPVote/eiCompare) to quantify vote dilution in US elections
* Met many inspiring [people](https://escience.washington.edu/data-science-for-social-good-teams-summer-2020/)
* Learned _a lot_. Some highlights:
  * The "human-centered design" approach to data science
  * How to collaborate on a coding project with a team spread across North America
  * The intricacies of voting rights litigation and empirical research on voting
  * Applied Bayesian statistics and spatial analysis in R

_**09/2019 - 05/2020: First year at Cornell**_

* Took courses in economics, statistics, computer science, sociology, and demography
* Started contributing to some ongoing research projects
* Became an affiliate of the Cornell Population Center ([CPC](https://cpc.cornell.edu/))
* Moved back to Canada when the pandemic forced classes online in March

_**06/2019 - 08/2019: Free summer**_

* Visited friends in Berlin, road-tripped through Italy
* Got engaged!
* Traveled with my fiancee through South America:
  * Fancy hotel in Cartegena
  * Snorkeling on the Galapagos Islands
  * Five day hike to Machu Picchu
  * Drove through the Bolivian Salt Flats
  
_**09/2017 - 05/2019: Multi Health Systems**_

* Did data science and product development research on a small "intrepreneurial" team called the Innovation Hub
* Moved to product management: 
  * Developed a business plan for a workplace mental health assessment product
  * Led a small team to help clients connect to the product's API

_**09/2016 - 08/2017: London School of Economics**_

* Took courses in sociology, political science, demography, and causal inference
* Met some amazing people from all over Europe and the rest of the world
* Took weekend trips to Croatia, Scotland, Barcelona
* First exposure to R, and to programming (addicted ever since)
* Presented at the European Association of Social Psychology Conference in Granada, Spain

_**09/2012 - 09/2016: University of Winnipeg**_

* Studied political psychology in an undergraduate research lab
* Wrote a book chapter and a text analysis paper