---
title: Applications and Recruitment Performance of Web-Based Respondent-Driven Sampling Scoping Review
author: "Ari Decter-Frain"
date: "04/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Yannick Helms and co-authors, 2021

This is a scoping review of recent web-based RDS studies. The authors document the sampling efforts of 18 such papers to uncover patterns in the types of practices that typically work for recruiting RDS samples.

The majority of the included studies either recruited seeds through targeted Facebook advertisements, and 6 combined online seeding with offline recruiting from interest groups or the researchers' own social networks. Studies recruited between 1 and 1015 seeds. Studies also varied in how they enabled recruiting (Facebook, Whatsapp, email, or passing contact info to the researcher), incentives given for recruitment, and total length of the study period. The authors caution that no definitive patterns have emerged from the literature yet, and it remains quite unclear whether these types of papers yield unbiased point estimates. They focus primarily on the success of the concrete sampling procedures - which studies tended to obtain many waves of recruits, which obtained large samples, and which did so the quickest? In general, they draw the following general lessons about web-based RDS designs:

* There exists a trade-off between the effort put into seed recruitment and the success of recruiting seeds. Studies that engage in-person with seeds and recruits achieve more waves of recruits from seeds on average than studies that do automated recruiting at scale via Facebook, etc.

* Studies not offering a guaranteed material (usually monetary) incentive for recruitment never reached more than six waves of recruiting.

* Studies that use online recruitment of seeds can obtain sufficient sample sizes an order of magnitude faster than in-person samples (eg. 72 hours compared to multiple months)

* The performance of online RDS depends at least somewhat on the digital literacy of the population under study, and the extent to which the network of the population has an online representation, either via an instant messenger, a social media platform, or some other means.